app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_add_user:
    defaults: { _controller: "AppBundle:Admin:addUser" }
    path: /add

admin_promote_user_list:
    defaults: { _controller: "AppBundle:Admin:promoteUserList" }
    path: /promote-user-list
    
admin_promote_user:
    defaults: { _controller: "AppBundle:Admin:promoteUser" }
    path: /promote-user
    
admin_demote_user:
    defaults: { _controller: "AppBundle:Admin:demoteUser" }
    path: /demote-user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

avanzu_admin_profile:
    defaults: { _controller: "AppBundle:Security:show" }
    path: /profile

avanzu_admin_logout:
    defaults: { _controller: "FOSUserBundle:Security:logout" }
    path: /logout