app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_add_user:
    defaults: { _controller: "AppBundle:Admin:addUser" }
    path: /add

admin_promote_user_list:
    defaults: { _controller: "AppBundle:Admin:promoteUserList" }
    path: /promote-user-list
    
admin_promote_user:
    defaults: { _controller: "AppBundle:Admin:promoteUser", id: 0 ,role: "ROLE_USER" }
    path: /promote-user/{id}/{role}/

admin_edit_user:
    defaults: { _controller: "AppBundle:Admin:editUser" }
    path: /edit-user
    
admin_demote_user:
    defaults: { _controller: "AppBundle:Admin:demoteUser",  id: 0 ,role: "ROLE_USER" }
    path: /demote-user/{id}/{role}/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

avanzu_admin_profile:
    defaults: { _controller: "AppBundle:Security:show" }
    path: /profile

avanzu_admin_logout:
    defaults: { _controller: "FOSUserBundle:Security:logout" }
    path: /logout