# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_admin_bundle.show_user_listener.class: AppBundle\EventListener\MyShowUserListener

services:
    my_admin_bundle.show_user_listener:
        class: %my_admin_bundle.show_user_listener.class%
        arguments: [ '@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }